name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          # Windows tests disabled until we fix CI (see #1)
          # - windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Clojure
        uses: DeLaGuardo/setup-clojure@13.0
        with:
          cli: latest

      - name: Run tests
        run: clojure -T:build ci
