name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Clojure
        uses: DeLaGuardo/setup-clojure@13.0
        with:
          tools-deps: "1.10.3.1040"

      - name: Run tests
        run: clojure -T:build ci
